language: node_js
node_js:
  - "stable"

cache:
  directories:
    - node_modules

jobs:
  include:
  # --------------------------------------------
    - stage: Build Application
      skip_cleanup: true
      before_script:
        - npm install
      script:
        - npm run build
      on:
        branch: master
  # --------------------------------------------
    - stage: Release to NPM
      before_deploy:
        - cd build
      deploy:
        provider: npm
        email: "$EMAIL"
        api_key: "$NPM_API_KEY"
        skip_cleanup: true
        on:
          branch: master