language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: Build
    before_script:
      - npm i -g makeshift && makeshift -s @bcoe -r registry.npmjs.org
    script:
      - npm install
      - npm run build
    before_deploy:
      - cd build/
    deploy:
      skip_cleanup: true
      keep-history: true
      provider: npm
      email: "$EMAIL"
      api_key: "$NPM_API_KEY"
      on:
        branch: master
        repo: drextlol/build-test
    
